"""Type stubs for the Rust native accelerator module."""

def normalize_text(text: str) -> str:
    """Fused NFKC + strip invisible + collapse whitespace + lowercase."""
    ...

class RustPatternExtractor:
    """Compiled multi-pattern extractor using RegexSet."""

    def __init__(self, patterns: dict[str, list[str]]) -> None: ...
    def extract(self, text: str) -> dict[str, float]: ...
    def find_pattern_spans(self, text: str) -> list[tuple[int, int]]: ...
    def has_any_match(self, text: str) -> bool: ...

class RustMotifMatcher:
    """Motif matcher with Aho-Corasick + optional fuzzy matching."""

    def __init__(self, motifs: dict[str, list[str]], threshold: int, use_fuzzy: bool) -> None: ...
    def find_matches(self, text: str, window_size: int, step: int) -> list[dict[str, object]]: ...
    def get_match_positions(self, text: str) -> list[tuple[int, int]]: ...

def text_to_features(text: str) -> list[dict[str, str]]:
    """Extract CRF features from text."""
    ...
